version: "3"
services:
  tensortrade:
    hostname: tensortrade
    build:
      context: .
    ports:
      - "8888:8888"
    volumes:
        - ./examples:/tensortrade/examples 
        - ./tensortrade:/tensortrade/tensortrade
    command: jupyter notebook --ip='*' --port=8888 --no-browser --allow-root ./examples/
    network_mode: host
  tensorboard:
    hostname: tensorboard
    build:
      context: .
    ports:
      - "6006:6006"
    volumes:
        - ./examples:/tensortrade/examples
        - ./tensortrade:/tensortrade/tensortrade
    command: tensorboard --logdir ./examples/logs
    network_mode: host